[package]
name = "quill"
version = "0.1.0"
edition = "2021"
description = "A Middle English inspired quantum programming language!"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.6"
pest_derive = "2.6"
